# Day2_Python and Cv2


# 索引
[資料初始化](#資料初始化)

[讀取特徵影像](#讀取特徵影像)

[分析特徵影像的特徵值](#分析特徵影像的特徵值)

[計算待識別影像的特徵值](#計算待識別影像的特徵值)

[識別](#識別)

In [1]:
import cv2
import numpy as np

## 資料初始化

In [2]:
#讀取樣本（特徵）圖像的值
s='image\\'  #圖像所在路徑
num=100 #共有樣本數量
row=240 #每個數字圖像的行數
col=240 #每個數字圖像的列數
a=np.zeros((num,row,col)) #用來存儲所有樣本的數值
print(a.shape)

(100, 240, 240)


## 讀取特徵影像

In [3]:
n=0 #用來存儲當前圖像的編號
for i in range(0,10):
    for j in range(1,11):
        a[n,:,:]=cv2.imread(s+str(i)+'\\'+str(i)+'-'+str(j)+'.bmp',0)
        n=n+1

In [4]:
print(a[0,::])

[[255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]


In [5]:
print(a[0,::].shape)

(240, 240)


##  分析特徵影像的特徵值

In [6]:
#提取樣本圖像的特徵
feature=np.zeros((num,round(row/5),round(col/5))) #用來存儲所有樣本的特徵值
#print(feature.shape)  #看看feature的shape長什麼樣子
#print(row)            #看看row的值，有多少個特徵（100）個

for ni in range(0,num):
    for nr in range(0,row):
        for nc in range(0,col):
            if a[ni,nr,nc]==255:
                feature[ni,int(nr/5),int(nc/5)]+=1
f=feature   #簡化變量名稱

## 計算待識別影像的特徵值

In [7]:
#####計算當前待識別圖像的特徵值
o=cv2.imread('image\\test\\5.bmp',0) #讀取待測圖像
##讀取圖像值
of=np.zeros((round(row/5),round(col/5))) #用來存儲測試圖像的特徵值
for nr in range(0,row):
    for nc in range(0,col):
        if o[nr,nc]==255:
            of[int(nr/5),int(nc/5)]+=1


## 識別

In [8]:
###開始計算，數字識別，計算最近的times個數字是誰，判斷結果
d=np.zeros(100)
for i in range(0,100):
    d[i]=np.sum((of-f[i,:,:])*(of-f[i,:,:]))
print(d)
d=d.tolist()
temp=[]
Inf = max(d)
print(Inf)
k=7
for i in range(k):
    temp.append(d.index(min(d)))
    d[d.index(min(d))]=Inf  #將最大值指派到陣列中
print(temp)   #看看都被識別為哪些特徵值了

[  96066.   85142.  110285.  110153.  102270.  103889.  103948.  100054.
  112656.   99778.   86995.   84424.   84677.   83273.   82476.   82803.
   83868.   82677.   84338.   84269.   95855. 1333586.   91477.  102119.
  107335.  105874.  108784.  111414.  114757.  112354.   79948.   97797.
  107031.   78375.   85575.  107129.  111396.  105933.  116503.  112122.
  108857.  106114.  102126.  103560.  101034.  105016.  111375.  110900.
  110628.  108814.   87223.   87918.   95230.   88730.   79073.   82151.
   94188.   86252.   77185.   91800.   88331.  108362.  121314.   89836.
  143935.  108946.  109578.   97324.   99419.  120538.  102910.  102939.
  100465.  102443.   97068.   88816.  106088.  100535.  101622.  104550.
  117031.  122261.  118118.  127061.  125294.  111937.  128592.  108484.
  109604.  122142.  112495.  112658.  114000.  106094.  101869.  114693.
  127703.  109004.  105606.  117819.]
1333586.0
[58, 33, 54, 30, 55, 14, 17]


In [9]:
temp=[i/10 for i in temp]

#數組r用來存儲結果，r[0]表示k近鄰中0的個數，r[n]K近鄰中n的個數
r=np.zeros(10)
for i in temp:
    r[int(i)]+=1
#print(r)
print('當前的數字可能為:'+str(np.argmax(r)))

當前的數字可能為:5


## 處理training set

In [10]:
#將feature處理為單行形式
train = feature[:,:].reshape(-1,round(row/5)*round(col/5)).astype(np.float32)
#print(train.shape)
#貼標籤，需要注意range(0,100)不是range(0,101)
trainLabels = [int(i/10)  for i in range(0,100)]
trainLabels=np.asarray(trainLabels)
#print(*trainLabels)   #打印測試看看標籤值