# Day2_Python and Cv2


# 索引
[資料初始化](#資料初始化)

[讀取特徵影像](#讀取特徵影像)

[分析特徵影像的特徵值](#分析特徵影像的特徵值)

[計算待識別影像的特徵值](#計算待識別影像的特徵值)

[識別](#識別)

In [ ]:
import cv2
import numpy as np

## 資料初始化

In [ ]:
#讀取樣本（特徵）圖像的值
s='image\\'  #圖像所在路徑
num=100 #共有樣本數量
row=240 #每個數字圖像的行數
col=240 #每個數字圖像的列數
a=np.zeros((num,row,col)) #用來存儲所有樣本的數值
print(a.shape)

(100, 240, 240)


## 讀取特徵影像

In [ ]:
n=0 #用來存儲當前圖像的編號
for i in range(0,10):
    for j in range(1,11):
        a[n,:,:]=cv2.imread(s+str(i)+'\\'+str(i)+'-'+str(j)+'.bmp',0)
        n=n+1

In [ ]:
print(a[0,::])

[[255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]


In [ ]:
print(a[0,::].shape)

(240, 240)


##  分析特徵影像的特徵值

In [ ]:
#提取樣本圖像的特徵
feature=np.zeros((num,round(row/5),round(col/5))) #用來存儲所有樣本的特徵值
#print(feature.shape)  #看看feature的shape長什麼樣子
#print(row)            #看看row的值，有多少個特徵（100）個

for ni in range(0,num):
    for nr in range(0,row):
        for nc in range(0,col):
            if a[ni,nr,nc]==255:
                feature[ni,int(nr/5),int(nc/5)]+=1
f=feature   #簡化變量名稱

## 將feature處理為單行形式

In [ ]:
train = feature[:,:].reshape(-1,round(row/5)*round(col/5)).astype(np.float32) 
print(train.shape)
#貼標籤，需要注意range(0,100)不是range(0,101)
trainLabels = [int(i/10)  for i in range(0,100)]
trainLabels=np.asarray(trainLabels)
print(*trainLabels)   #打印測試看看標籤值
print(type(trainLabels))   #打印測試看看標籤值

(100, 2304)
0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6 6 7 7 7 7 7 7 7 7 7 7 8 8 8 8 8 8 8 8 8 8 9 9 9 9 9 9 9 9 9 9
<class 'numpy.ndarray'>


## 計算待識別影像的特徵值

In [ ]:
#####計算當前待識別圖像的特徵值
o=cv2.imread('image\\test\\5.bmp',0) #讀取待測圖像
##讀取圖像值
of=np.zeros((round(row/5),round(col/5))) #用來存儲測試圖像的特徵值
for nr in range(0,row):
    for nc in range(0,col):
        if o[nr,nc]==255:
            of[int(nr/5),int(nc/5)]+=1


## 識別

In [ ]:
test=of.reshape(-1,round(row/5)*round(col/5)).astype(np.float32) 
#調用函數識別
knn=cv2.ml.KNearest_create()
knn.train(train,cv2.ml.ROW_SAMPLE, trainLabels)
ret,result,neighbours,dist = knn.findNearest(test,k=7)
print("當前隨機數可以判定為類型：", result)
print("距離當前點最近的7個鄰居是：", neighbours)
print("7個最近鄰居的距離 : ", dist)

當前隨機數可以判定為類型： [[5.]]
距離當前點最近的5個鄰居是： [[5. 3. 5. 3. 5. 1. 1.]]
5個最近鄰居的距離 :  [[77185. 78375. 79073. 79948. 82151. 82476. 82677.]]


## 